export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const GET_TRENDING = 'GET_TRENDING'
export const GET_RECENT = 'GET_RECENT'
export const GET_FEATURED = 'GET_FEATURED'
export const POSTS_ERROR = 'POSTS_ERROR'

// export const SEARCH_FILE = 'SEARCH_FILE';
// export const CLEAR_SEARCH = 'CLEAR_SEARCH';
// export const REMOVE_FILE = 'REMOVE_FILE';
// export const ADD_FILE = 'ADD_FILE';
// export const EDIT_FILE = 'EDIT_FILE';
// export const CLEAR_EDIT = 'CLEAR_EDIT';
// export const UPDATE_FILE = 'UPDATE_FILE';
// export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// export const REGISTER_FAIL = 'REGISTER_FAIL';
// export const USER_LOADED = 'USER_LOADED';
// export const AUTH_ERROR = 'AUTH_ERROR';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAIL = 'LOGIN_FAIL';
// export const LOGOUT = 'LOGOUT';
// export const GET_FILES = 'GET_FILES';
// export const FILES_ERROR = 'FILES_ERROR';
// export const CLEAR_FILES = 'CLEAR_FILES';
// export const CLEAR_ERRORS = 'CLEAR_ERRORS';
